// debugger;
export const translates = {
    hy: {
        titleText: 'Yandex Taxi - Banants Taxi',
        aboutBtn: 'Մեր մասին',
        rentalBtn: 'Օրավարձով մեքենաներ',
        servicesBtn: 'Ծառայություններ',
        warningText: 'Ողջույն հարգելի գործընկեր, հարցերի դեպքում զանգահարեք կամ գրեք նշված հեռախոսահամարով!+37477636706',
        questionText: 'Ինչու՞ համագործակցել մեզ հետ',
        one_text: 'Սեփական տաքսիների պարկ/Ցածր տոկոսադրույք: 3.9%',
        tree_text: 'Ավտոմեքենաների վարձույթի ցածր գներ 6000-ից դ./օրը',
        five_text: 'Ընկերության հաշվին սպասարկում/ապահովագրություն',
        four_text: 'Մշտապես ապահովում ենք մեր մեքենաների տեխնիկական վիճակը',
        six_text: 'Մեր պարկում կա ավելի քան 40 ավտոմեքենա ցանկացած տարիֆի համար/Dostavka/Start/Komfort/Komfort+/Minivan/Business',
        seven_text: 'Բոնուս միանալիս մեր պարկ, 2000 դ․/մշտական ​​բոնուսներ',
        eight_text: 'Ակնթարթային վճարումներ առանց ուշացումների',
        nine_text: '24/7 աջակցություն և օգնություն ցանկացած իրավիճակում',
        ten_text: 'Արագ միացում Yandex-GO ընդամենը 10 րոպեում',
        twoo_text: 'Ձեր  մեքենանի սրահի քիմմաքրում/լուսարձակների փայլեցում մինչ դուք հանգստանում եք մեր գրասենյակում համեղ սուրճով և տորթով',
        yearTitle: 'Տարեթիվ:',
        akpp_info: 'Ավտոմատ',
        motor_title: 'Շարժիչ:',
        motor_info: '2.5',
        fuel_title: 'Վառելիք:',
        fuel_info: 'Հեղուկ-գազ',
        minimum_title: 'Նվազագույնը:',
        minimum_info: '3 ամիս',
        deposite_title: 'Ավանդ:',
        deposite_info: '60000',
        conditioner_title: 'Օդորակիչ:',
        conditioner_info: 'Կա',
        camera_title: 'Հետևի տեսախցիկ:',
        camera_info: 'Կա',
        control_title: 'Կրուիզ կոնտրոլ:',
        control_info: 'Կա',
        price_title: 'Գինը սկսած 11000-ից<br>կիրակին վարորդին<br>Ձմեռը զեղչ'
    },
    ru: {
        titleText: 'Яндекс Такси - Бананц Такси',
        aboutBtn: 'О нас',
        rentalBtn: 'Аренда автомобилей',
        servicesBtn: 'Услуги',
        warningText: 'Здрайствуйте уважаемый колега при вопросах звоните или пишите по указаному номеру!+37477636706',
        questionText: 'Почему стоит сотрудничать с нами?',
        one_text: 'Собственный таксопарк/Низкий тариф. 3,9%',
        tree_text: 'Низкие цены на аренду авто от 6000 драмов/сутки.',
        five_text: 'Сервис/страховка за счет компании',
        four_text: 'Мы постоянно обеспечиваем техническое состояние наших автомобилей',
        six_text: 'В нашем автопарке более 40 автомобилей на любой тариф/Dostavka/Start/Komfort/Komfort+/Minivan/Business',
        seven_text: 'Бонус при присоединении к нашему парку, 2000 д./постоянные бонусы',
        eight_text: 'Мгновенные выплаты без задержек',
        nine_text: 'Круглосуточная поддержка и помощь в любой ситуации',
        ten_text: 'Быстрое подключение к Яндекс-ГО всего за 10 минут',
        twoo_text: 'Химчистка салона/полировка фар вашего автомобиля, пока вы отдыхаете в нашем офисе за вкусным кофе и пирожным',
        yearTitle: 'Год-выпуска',    
        akpp_info: 'Автомат',
        motor_title: 'Двигатель::',
        motor_info: '2.5',
        fuel_title: 'Топливо:',
        fuel_info: 'Пропан',
        minimum_title: 'Минимум:',
        minimum_info: '3 месяца',
        deposite_title: 'Депозит::',
        deposite_info: '60000',
        conditioner_title: 'Кондиционер:',
        conditioner_info: 'есть',
        camera_title: 'Задняя камера:',
        camera_info: 'есть',
        control_title: 'Круиз-контроль:',
        control_info: 'есть',
        price_title: 'Цена от 11000<br>воскресения водителю<br>зимой скидка'
    },
    en: {
        titleText: 'Yandex Taxi - Banants Taxi',
        aboutBtn: 'About us',
        rentalBtn: 'Car rental',
        servicesBtn: 'Services',
        warningText: 'Hello dear colleague, if you have any questions, call or write to the number provided!+37477636706',
        questionText: 'Why cooperate with us?',
        one_text: 'Private taxi fleet/Low tariff. 3.9%',
        tree_text: 'Low prices for car rental from 6000 AMD/day.',
        five_text: 'Service/insurance at the expense of the company',
        four_text: 'We constantly ensure the technical condition of our cars',
        six_text: 'Our fleet includes more than 40 cars for any tariff/Dostavka/Start/Komfort/Komfort+/Minivan/Business',
        seven_text: 'Bonus when joining our park, 2000 rubles/permanent bonuses',
        eight_text: 'Instant payments without delays',
        nine_text: '24/7 support and assistance in any situation',
        ten_text: 'Quick connection to Yandex-GO in just 10 minutes',
        twoo_text: 'Dry cleaning/polishing your cars headlights while you relax in our office with delicious coffee and cake',
        yearTitle: 'Year of issue:',    
        akpp_info: 'Machine',
        motor_title: 'Engine:',
        motor_info: '2.5',
        fuel_title: 'Fuel:',
        fuel_info: 'Propane',
        minimum_title: 'Minimum:',
        minimum_info: '3 months',
        deposite_title: 'Deposit:',
        deposite_info: '60000',
        conditioner_title: 'Air conditioner:',
        conditioner_info: 'There is',
        camera_title: 'Rear camera:',
        camera_info: 'There is',
        control_title: 'Cruise control:',
        control_info: 'There is',
        price_title: 'Price from 11000<br>resurrection to the driver<br>winter discount'
    }
};